config/routes.rb
Gameballs::Application.routes.draw do
  resources :games 
  get 'games/:game_id' => 'games#show', :as => 'game_by_name'
  get 'genres' => 'games#genres'
  get 'genre/:genre_id' => 'games#genres', :as => 'genre'
  get 'update_counts' => 'games#update_counts'
  root :to => 'games#index'

end

app/models/game.rb
require 'net/http'
require "net/https"
require 'open-uri'
require 'json'
class Game
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  has_and_belongs_to_many :genres
  has_many :viewstamps, :dependent => :destroy
  field :name, :type => String
  slug :name
  field :giantbomb_id, :type => String
  field :boxart_url, :type => String
  field :live, :type => String
  field :twitch_name, :type => String
  field :owned_name, :type => String
  field :owned_game_id, :type => String
  field :twitch_game_id, :type => String
  field :current_viewers, :type => Integer, :default => 0
  field :current_channels, :type => Integer, :default => 0
  field :last_update, :type => DateTime

  def self.update_counts
    Game.each do |gm|
      gm.current_viewers = 0
      gm.current_channels = 0
      gm.save
    end
  	timestamp = Time.now
  	Game.get_twitch(timestamp)
    puts 'done with twitch'
  	# Game.get_owned(timestamp)
   #  puts 'done with own3d'
    vss = Viewstamp.where(:created_at.gte => 30.minutes.ago)
  	vss.each do |vs|
  		vs.game.update_attribute(:current_viewers, vs.viewers)
      vs.game.update_attribute(:current_channels, vs.channels)
	  end
    puts 'done updating current viewers and channels'
    Genre.update_all_games_counts
    puts 'done updating (all genreses) games counts'
    puts 'totally done'
  end
  #both are class methods, not instance mathods
  def self.get_twitch(timestamp)
  	url = URI.parse("https://api.twitch.tv/kraken/games/top?limit=100") 
  	http = Net::HTTP.new(url.host, url.port)
		http.use_ssl = true
		http.verify_mode = OpenSSL::SSL::VERIFY_NONE
		request = Net::HTTP::Get.new(url.request_uri)
  	response = JSON.parse(http.request(request).body)

  	top = response['top']
  	top.each do |gm|
  		name = gm['game']['name']
  		twitch_id = gm['game']['_id']
  		viewers = gm['viewers'].to_i
  		channels = gm['channels'].to_i


      #find games whose name starts with 'the_game_name'
      re = Regexp.new(name, 'i')
      games = Game.where(name: re)
      #if none exist
      if games.count == 0
        #create one
        the_game = Game.find_or_initialize_by(twitch_name: name)
      else
        #select the first one
        the_game = games.first
        the_game.twitch_name = name
      end
  		if the_game.name == nil
  			the_game.name = name
  		end
      if the_game.giantbomb_id == nil
        the_game.giantbomb_id = gm['game']['giantbomb_id']
      end
      if the_game.boxart_url == nil
        the_game.boxart_url = gm['game']['box']['medium']
      end
  		vs = the_game.viewstamps.find_or_initialize_by(timestamp: timestamp)
  		vs.viewers += viewers
  		vs.channels += channels
  		vs.twitch_viewers = viewers
  		vs.twitch_channels = channels
  		vs.save
      the_game.last_update = timestamp
      the_game.save
      if the_game.genres.any? == false and the_game.giantbomb_id != nil
        puts the_game.giantbomb_id
        gn_uri = 'http://api.giantbomb.com/game/'+the_game.giantbomb_id+'/?format=json&field_list=genres&api_key=569f949a9144b175988ed3179acde3139464a4eb'
        gn_url = URI.parse(gn_uri)
        gn_rsl = Net::HTTP.get(gn_url)
        gn_response = JSON.parse(gn_rsl)
        if gn_response['error'] == 'OK'
          gn_response['results']['genres'].each do |gn|
            the_gn = Genre.find_or_initialize_by(name: gn['name'])
            the_gn.giantbomb_id = gn['id']
            the_gn.save
            the_gn.games.push(the_game)
          end
        end
      end
  	end
  end
  def self.get_owned(timestamp)
  	url = URI.parse("http://api.own3d.tv/rest/live/list.json?limit=1000")
  	rsl = Net::HTTP.get(url)
  	live_streams = JSON.parse(rsl)
  	live_streams.each do |st|
      if st['game_name'] != nil
        if st['game_name'] == 'Game'
          puts 'wtf!'
          puts st
        end
    		name = st['game_name']
        #find games whose name starts with 'the_game_name'
        re = Regexp.new(name, 'i')
        games = Game.where(name: re)
        #if none exist
        if games.count == 0
          #create one
      		the_game = Game.find_or_initialize_by(owned_name: name)
        else
          #select the first one
          the_game = games.first
          if the_game.owned_name == nil
            the_game.owned_name = name
          end
        end
        if the_game.name == nil
          the_game.name = name
        end
  	  	vs = the_game.viewstamps.find_or_initialize_by(timestamp: timestamp)
    		vs.viewers += st['live_viewers'].to_i
    		vs.owned_viewers += st['live_viewers'].to_i
    		vs.owned_channels += 1
    		vs.channels += 1
  	  	vs.save
        the_game.last_update = timestamp
        the_game.save
      end
  	end
	end
end

app/controllers/games_controller.rb
require 'csv'
require 'json'
class GamesController < ApplicationController
  include ActionView::Helpers::JavaScriptHelper

  def genres
    genre_id = params[:genre_id]
    if genre_id != nil
      @genre = Genre.find_by(giantbomb_id: genre_id)
      @games = @genre.games
    else
      @games = Game.all
    end
    @games = @games.where(:current_viewers.gt => 0)
    @games = @games.where(:last_update.gte => 1.day.ago)
    @games = @games.order_by([:current_viewers , :desc]) 
    @genres = Genre.where(:games_count.ne => 0)  
    @genres = @genres.order_by([:games_count, :desc])
  end

  def update_counts
    #move to delayed method
    Game.update_counts
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Reloading viewer counts' }
    end
  end

  # GET /games
  # GET /games.json
  def index
    days_back = 3
    if params[:days_back]
      if params[:days_back].to_i > 0
        days_back = params[:days_back].to_i
      end
    else
      params[:days_back] = days_back.to_s
    end
    @games = Game.where(:last_update.gte => days_back.days.ago)
    @games = @games.order_by([:current_viewers, :desc])
    @games = @games.limit(25)
    gs = @games.limit(10)
    jsn = {}

    gs.each do |g|
      viewstamps = g.viewstamps.where(:timestamp.gte => days_back.days.ago)
      #viewstamps = viewstamps.order_by([:timestamp, :desc])
      gname = escape_javascript(g.name)
      viewstamps.each do |vs|
        ts = vs.timestamp.to_s
        if jsn[ts] == nil
          jsn[ts] = {}
        end
        if jsn[ts]['Date'] == nil
          jsn[ts]['Date'] = ts
        end
        jsn[ts][gname] = vs.viewers
      end
    end

    g_header = ['Date']
    gs.each do |g|
      g_header.push(escape_javascript(g.name))
    end
    g_rows = [g_header.join(',')]
    jsn.values.each do |jn|
      a_row = []
      g_header.each do |gh|
        if jn[gh] != nil
          a_row.push(jn[gh])
        else
          a_row.push(0)
        end
      end
      g_rows.push(escape_javascript(a_row.join(',')))
    end
    csv_string = g_rows.join('\n')
    @graph_data = csv_string

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    if params[:id]
      @game = Game.find(params[:id])
    else
      s = CGI.unescape(params[:game_id])
      re = Regexp.new(s, 'i')
      puts s
      puts re
      #@game = Game.where(:name => re).first
      #if @game == nil
      @game = Game.first
      #end
    end
    days_back = 7
    if params[:days_back]
      if params[:days_back].to_i > 0
        days_back = params[:days_back].to_i
      end
    else
      params[:days_back] = days_back.to_s
    end
    jsn = {}
    @viewstamps = @game.viewstamps.where(:created_at.gte => days_back.days.ago)
    @viewstamps = @viewstamps.order_by([:created_at, :desc])
    jsn['Date'] = []
    @viewstamps.each do |vs|
      jsn['Date'].push(vs.created_at)
    end
    col = []
    @viewstamps.each do |vs|
      col.push(vs.viewers)
    end
    jsn[escape_javascript(@game.name)] = col
    g_names = jsn.keys.join(',')
    rows_arr = [g_names]
    counter = 0
    no_games = jsn.keys.length - 1
    #do this as many times as there are rows
    jsn['Date'].length.times do
      rs = []
      #do this for each column
      jsn.values.each do |cl|
        rs.push(cl[counter])
      end
      counter += 1
      rows_arr.push(rs.join(','))
    end
    @graph_data = rows_arr.join('\n')

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label "Name:" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Own3d.tv EXACT Name:" %><br />
    <%= f.text_field :owned_name %>
  </div>
  <div class="field">
    <%= f.label "Twitch.tv EXACT Name:" %><br />
    <%= f.text_field :twitch_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/genres.html.erb
<div class='span12'>
	<ul class="nav nav-pills">
	  <li id='all'><a href="#"><%= Game.where(:current_viewers.gt => 0).count %> - All</a></li>
	  <% @genres.each do |gnr| %>
	  	<li id='<%= gnr.giantbomb_id %>'>
	  		<a href="<%= genre_path(URI.encode(gnr.giantbomb_id)) %>">
	  			<%= gnr.games.count %> - <%= gnr.name %>
				</a>
	  	</li>
	  <% end %>
	</ul>
  <script type="text/javascript">
  	var active_genre = '<%= params[:genre_id] %>';
  	if(active_genre != ''){
  		$('#'+active_genre).addClass('active');
  	}else{
  		$('#all').addClass('active');
  	}
  	console.log(active_genre);
  </script>
</div>
<hr>
<div class='row-fluid'>	
	<ul class="thumbnails">
		<% @games.each do |game| %>
		  <li class='span2'>
		  	<div class="thumbnail">
			  	<a href="http://twitch.tv/directory/game/<%= URI.encode(game.name) %>">
				      <img src="<%= game.boxart_url %>" alt="<%= game.name %>">
		    	</a>
		    	<div style='height: 44px;'>
			      <h5><%= game.name %></h5>
					</div>
		      <%= link_to game do %>
		      <small><%= game.current_viewers %> viewers | <%= game.current_channels %> channels</small>
		      <% end %>
		  	</div>
		  </li>
		<% end %>
	</ul>
</div>
<script type="text/javascript">
function fixThumbnailMargins() {
    $('.row-fluid .thumbnails').each(function () {
        var $thumbnails = $(this).children(),
            previousOffsetLeft = $thumbnails.first().offset().left;
        $thumbnails.each(function () {
            var $thumbnail = $(this),
                offsetLeft = $thumbnail.offset().left;
            if (offsetLeft < previousOffsetLeft) {
                $thumbnail.css('margin-left', 0);
            }
            previousOffsetLeft = offsetLeft;
        });
    });
}
fixThumbnailMargins();


</script>
<br>
<!-- 
giantbomb api key
569f949a9144b175988ed3179acde3139464a4eb

get genres of a game
http://api.giantbomb.com/game/24024/?format=json&field_list=genres&api_key=569f949a9144b175988ed3179acde3139464a4eb

genre 
has_and_belongs_to_many games

game
has_and_belongs_to_many genres
 -->

app/views/games/index.html.erb
<small>Nov.16: Something broke with Own3d.tv I need to look closer. Own3d.tv numbers unavailable for now.</small>
<div style='width: 100%;' id="graphdiv"></div>
<small>Numbers updated <%= time_ago_in_words(Viewstamp.last.created_at) %> ago</small>
<form method='get' class='form-inline pull-right'>
  <fieldset>
      <%= select_tag 'days_back', options_for_select(["1", "3", "7", "30", '9001' ], params[:days_back]), :class => 'input-mini' %>
    <button type="submit" class="btn">Days of Data</button>
  </fieldset>
</form>
<script type="text/javascript">
  var graph_data = '<%= @graph_data %>';
  g = new Dygraph(
    // containing div
    document.getElementById("graphdiv"),
    // CSV or path to a CSV file.
    graph_data,
    {
      rollPeriod: 1,
      showRoller: false
    }
  );
</script>
<table class='table table-striped table-bordered table-hover table-condensed'>
  <thead class='info'>
    <tr>
      <th>Game Name</th>
      <th>Recent Viewers</th>
      <th>- just Own3d</th>
      <th>- just Twitch</th>
      <th>Recent Channels</th>
      <th>- just Own3d</th>
      <th>- just Twitch</th>
      <th>Own3d Name</th>
      <th>Twitch Name</th>
  <!--     <th></th>
      <th></th>
      <th></th> -->
    </tr>
  </thead>
<tbody>
<% @games.each do |game| %>
  <tr>
    <td><%= link_to game.name, game %></td>
    <% if game.viewstamps.any? %>
      <td><%= game.viewstamps.last.viewers %></td>
      <td><%= game.viewstamps.last.owned_viewers %></td>
      <td><%= game.viewstamps.last.twitch_viewers %></td>
      <td><%= game.viewstamps.last.channels %></td>
      <td><%= game.viewstamps.last.owned_channels %></td>
      <td><%= game.viewstamps.last.twitch_channels %></td>
    <% end %>
    <td><%= game.owned_name %></td>
    <td><%= game.twitch_name %></td>
<!--     <td><%#= link_to 'Show', game %></td>
    <td><%#= link_to 'Edit', edit_game_patd(game) %></td>
    <td><%#= link_to 'Destroy', game, confirm: 'Are you sure?', metdod: :delete %></td> -->
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<h4><%= @game.name %></h4>
<div style='width: 100%;' id="graphdiv"></div>
<small>Numbers updated <%= time_ago_in_words(@game.viewstamps.last.created_at) %> ago</small> | 
<small><%= @game.twitch_name %> on twitch and <%= @game.owned_name %> on own3d</small>
<form method='get' class='form-inline pull-right'>
	<fieldset>
			<%= select_tag 'days_back', options_for_select(["1", "3", "7", "30", '9001' ], params[:days_back]), :class => 'input-mini' %>
    <button type="submit" class="btn">Days of Data</button>
	</fieldset>
</form>
<script type="text/javascript">
  var graph_data = '<%= @graph_data %>';
  g = new Dygraph(
    // containing div
    document.getElementById("graphdiv"),
    // CSV or path to a CSV file.
    graph_data,
    {
      rollPeriod: 1,
      showRoller: false
    }
  );
</script>

<table class='table table-striped table-bordered table-hover table-condensed'>
  <thead class='info'>
    <tr>
      <th>Viewstamp Time</th>
      <th>Total Viewers</th>
      <th>- just Own3d</th>
      <th>- just Twitch</th>
      <th>Total Channels</th>
      <th>- just Own3d</th>
      <th>- just Twitch</th>
<!--       <th>Top Streamer</th>
      <th>- stream title</th>
      <th>- view count</th> -->
    </tr>
  </thead>
<tbody>
<% @viewstamps.order_by([:created_at, :desc]).limit(100).each do |vs| %>
  <tr>
    <td><%= time_tag vs.created_at %></td>
    <td><%= vs.viewers %></td>
    <td><%= vs.owned_viewers %></td>

    <td><%= vs.twitch_viewers %></td>
    <td><%= vs.channels %></td>
    <td><%= vs.owned_channels %></td>

    <td><%= vs.twitch_channels %></td>
<!-- 		<td><%= 'top streamer' %></td>
    <td><%= 'stream title' %></td>
    <td><%= 'stream viewers' %></td> -->
  </tr>
<% end %>
</tbody>
</table>

<br />


<%#= @game.attributes.to_s %>
<%#= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>