config/routes.rb
Gameballs::Application.routes.draw do
  resources :games 
  get 'games/:game_id' => 'games#show', :as => 'game_by_name'
  get 'genres' => 'games#genres'
  get 'genre/:genre_id' => 'games#genres', :as => 'genre'
  get 'update_counts' => 'games#update_counts'
  root :to => 'games#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GameBalls" %></title>
    <meta name="description" content="measuring the eyeballs on games">
    <meta name="author" content="Hayk Saakian">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container-fluid">
          <span class='brand'><%= link_to_unless_current 'GameBalls', root_url %> - measuring the eyeballs on games</span>
          <div class='pull-right'>
            <ul class="nav">
              <!-- <li><%#= link_to 'Update viewer counts',update_counts_path %></li> -->
              <li><%= link_to 'Browse Games by Genre', genres_path %></li>
            </ul>
          </div>
        </div>
      </nav>

    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
      <script type="text/javascript"><!--
        google_ad_client = "ca-pub-9515182789223023";
        /* Header Ad for GameBalls.info */
        google_ad_slot = "5854748776";
        google_ad_width = 728;
        google_ad_height = 90;
        //-->
        </script>
      <script type="text/javascript"
      src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        $('#spacer').show();
      </script>
      
              <%= yield %>
            </div>
          </div>
        </div>
          <footer>
            <br>
            by <%= link_to "Hayk Saakian", "http://twitter.com/hayksaakian" %>
          </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>